tunnel: b6f238db-50d5-4c9b-a59d-89fffa203a5c
credentials-file: C:\Users\alxpa\.cloudflared\b6f238db-50d5-4c9b-a59d-89fffa203a5c.json

ingress:
  - hostname: eduflexlms.se
    service: http://localhost:5173
  - hostname: www.eduflexlms.se
    service: http://localhost:5173
  - hostname: api.eduflexlms.se
    service: http://localhost:8080
  - hostname: storage.eduflexlms.se
    service: http://localhost:9000
  - service: http_status:404
