apiVersion: v1
kind: Secret
metadata:
  name: eduflex-secrets
  namespace: eduflex
type: Opaque
stringData:
  # Database
  POSTGRES_PASSWORD: "eduflex_secure_password_2026"
  SPRING_DATASOURCE_PASSWORD: "eduflex_secure_password_2026"
  
  # JWT
  JWT_SECRET: "your-256-bit-secret-key-change-this-in-production"
  
  # MinIO
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin123"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
  
  # Keycloak
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"
  KC_DB_PASSWORD: "keycloak_password"
