apiVersion: v1
kind: Secret
metadata:
  name: eduflex-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eduflex.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database
  POSTGRES_PASSWORD: "gotland81"
  SPRING_DATASOURCE_PASSWORD: "gotland81"
  
  # MinIO
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  
  # Keycloak
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  
  # JWT
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

  # Grafana
  GRAFANA_ADMIN_PASSWORD: "admin"
